#!/bin/bash

bin=/home/justice-reaper/.config/bin

printf 'Xcursor.theme: Windows-10-Alt-Light\nXcursor.size: 24\n' | xrdb -merge
xsetroot -xcf /usr/share/icons/Windows-10-Alt-Light/cursors/left_ptr 24

if [ -r "$bin/brightness" ]; then
    brightness=$(cat "$bin/brightness")
    if [ -n "$brightness" ]; then
        brightnessctl set "$brightness"
    fi
fi

if [ "$(cat "$bin/nightlight-status")" = "On" ]; then
    kelvin=$(cat "$bin/nightlight")
    if [ -n "$kelvin" ]; then
        redshift -P -O "$kelvin" &>/dev/null
    fi
fi
