#!/bin/sh
if grep -qE "^\S+ / overlay " /proc/mounts; then
    echo "==> Skipped (booted from a GRUB snapshot, snapshots cannot be created)"
    exit 0
fi
exec /usr/share/libalpm/scripts/snap-pac "$@"
